#!/bin/bash

echo "=== CLEANUP UNNECESSARY FILES ==="
echo ""

# Array of files to delete
files_to_delete=(
    # Documentation files (temporary/duplicate)
    "ALL_FIXES_SUMMARY.md"
    "AUDIT_COMPLETE_SUMMARY.md"
    "BACA_INI_DULU.md"
    "CARA_DEPLOY_VERCEL.md"
    "CARA_TEST_GAMBAR.md"
    "CLOUDINARY_ANALYSIS.md"
    "CLOUDINARY_REMOVAL_COMPLETE.md"
    "COMPLETE_FIX_GUIDE.md"
    "COMPLETE_IMAGE_SYSTEM_REBUILD.md"
    "COMPREHENSIVE_AUDIT_COMPLETE.md"
    "DEBUG_500_ERROR.md"
    "DEBUG_IMAGE_ISSUE.md"
    "DEPLOY_CHECKLIST.md"
    "DEPLOYMENT_COMMANDS.md"
    "DEPLOYMENT_INSTRUCTIONS.md"
    "DEPLOYMENT_READY.txt"
    "DEPLOYMENT_STATUS.md"
    "DEPLOYMENT_SUMMARY.md"
    "DETAILED_TROUBLESHOOTING.md"
    "EMAIL_DEPLOYMENT_CHECKLIST.md"
    "EMAIL_SYSTEM_SUMMARY.md"
    "FILE_UPLOAD_COMPLETE_FIX.md"
    "FINAL_CHECKLIST.md"
    "FINAL_IMAGE_SYSTEM_DOCUMENTATION.md"
    "FIX_FINAL.md"
    "FIX_VIEW_ERROR.md"
    "GITHUB_ACTIONS_FIX.md"
    "GITHUB_PUSH_SUMMARY.md"
    "HOSTINGER_DEPLOYMENT_GUIDE.md"
    "HOSTINGER_DEPLOYMENT_SOLUTIONS.md"
    "HOSTINGER_GIT_DEPLOYMENT_FIX.md"
    "HOSTINGER_MANUAL_UPLOAD.md"
    "HOSTINGER_PRIVATE_REPO.md"
    "HOSTINGER_STEP_BY_STEP.md"
    "IMAGE_AUDIT_REPORT.md"
    "IMAGE_DISPLAY_COMPREHENSIVE_AUDIT.md"
    "IMAGE_DISPLAY_FIX_COMPLETE.md"
    "IMAGE_DISPLAY_FIX.md"
    "IMAGE_DISPLAY_STANDARDIZATION.md"
    "IMAGE_HELPER_QUICK_REFERENCE.md"
    "IMAGE_STORAGE_FIX.md"
    "INSTALLED_SKILLS_COMPLETE.md"
    "JASTIPHYPE_IMPROVEMENT_PLAN.md"
    "LANGKAH_PERBAIKAN_GAMBAR.md"
    "LANGKAH_SEKARANG.md"
    "LANGKAH_TERAKHIR.md"
    "MANUAL_DIAGNOSTIC_STEPS.md"
    "NEXT_STEPS.md"
    "NODE_VERSION_UPDATE.md"
    "PERBAIKAN_GAMBAR_FINAL.md"
    "PERBAIKAN_UPLOAD_FILE.md"
    "QUICK_DEPLOY.md"
    "QUICK_FIX_500.md"
    "QUICK_FIX_REFERENCE.md"
    "QUICK_START.md"
    "QUICK_SUMMARY.md"
    "RAILWAY_DEPLOYMENT.md"
    "README_DEPLOYMENT.md"
    "SOLUSI_GAMBAR_FINAL.md"
    "SOLUSI_PRIVATE_REPO_HOSTINGER.md"
    "START_HERE.md"
    "STATUS_DEPLOYMENT.md"
    "STORAGE_FIX_GUIDE.md"
    "STORAGE_FIX_WINDOWS.md"
    "SUMMARY_PERBAIKAN_GAMBAR.md"
    "TESTING_CHECKLIST.md"
    "TROUBLESHOOTING.md"
    "UPLOAD_FIX_SUMMARY.md"
    "VERCEL_500_ERROR_FIX.md"
    "VERCEL_BUILD_ERROR_FIX.md"
    "VERCEL_DEPLOY_FIXED.md"
    "VERCEL_DEPLOYMENT_TROUBLESHOOTING.md"
    "VERCEL_DEPLOYMENT.md"
    "VERCEL_ENV_COPY_PASTE.md"
    "VERCEL_ENV_SETUP.md"
    "VERCEL_ENV_VARIABLES.md"
    "VERCEL_ISSUES_COMPLETE_FIX.md"
    "VERCEL_PAYLOAD_FIX_FINAL.md"
    "VERCEL_PAYLOAD_TOO_LARGE_FIX.md"
    "VERCEL_QUICK_FIX.md"
    "VERIFICATION_COMPLETE.md"
    
    # Test/Debug PHP files
    "debug-banner-images.php"
    "debug-image-paths.php"
    "diagnose-production.php"
    "production-fix.php"
    "test-complete-image-system.php"
    "test-direct-access.php"
    "test-disk.php"
    "test-image-helper.php"
    "test-simple-route.php"
    "test-storage-fix.php"
    "test-storage-route.php"
    "verify-images.php"
    
    # Temporary scripts (keep only essential ones)
    "check-error-log.sh"
    "check-production-images.sh"
    "deploy-to-hostinger.ps1"
    "deploy-to-hostinger.sh"
    "deploy-vercel.bat"
    "deploy-vercel.sh"
    "download_assets.ps1"
    "download_missing_logos.ps1"
    "download.bat"
    "fix-500-error.sh"
    "force-fix-now.sh"
    "migrate-images-to-public.php"
    "start.sh"
    "sync-storage.bat"
    
    # Backup/unused config
    "Dockerfile.backup"
    ".dockerignore"
    ".nixpacks.json"
    ".vercelignore"
    "railway.toml"
    "vercel.json"
    ".env.vercel"
    
    # Other
    "build.zip"
    "skills-list.txt"
)

deleted_count=0
not_found_count=0

for file in "${files_to_delete[@]}"; do
    if [ -f "$file" ]; then
        rm "$file"
        echo "✅ Deleted: $file"
        ((deleted_count++))
    else
        echo "⚠️  Not found: $file"
        ((not_found_count++))
    fi
done

echo ""
echo "=== CLEANUP SUMMARY ==="
echo "✅ Deleted: $deleted_count files"
echo "⚠️  Not found: $not_found_count files"
echo ""
echo "📝 KEPT IMPORTANT FILES:"
echo "  - README.md (main documentation)"
echo "  - CUSTOM_ERROR_PAGES.md (error page guide)"
echo "  - EMAIL_SYSTEM_GUIDE.md (email setup guide)"
echo "  - HOSTINGER_403_FIX.md (403 error fix)"
echo "  - HOSTINGER_PRIVATE_REPO_SETUP.md (git setup)"
echo "  - HOSTINGER_SETUP.md (hosting setup)"
echo "  - GENERATE_SSH_KEY_WINDOWS.md (SSH key guide)"
echo "  - deploy-fix-images.sh (image deployment)"
echo "  - fix-database-paths.php (database fix)"
echo "  - fix-ssh-and-env.sh (SSH & env fix)"
echo "  - migrate-private-to-public.php (image migration)"
echo "  - nuclear-fix.sh (emergency fix)"
echo ""
echo "✅ CLEANUP COMPLETE!"
