[build]
builder = "NIXPACKS"

[deploy]
startCommand = "chmod +x ./railway/init-app.sh && sh ./railway/init-app.sh && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
